server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: categories-service
          uri: http://categories-service:8080
          predicates:
            - Path=/categories-service/**
    kubernetes:
      discovery:
        enabled: true
        namespaces: default
        metadata:
          add-ports: true
        service-labels:
            app: spring-microservice

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.kubernetes: DEBUG
    org.springframework.cloud.kubernetes.client: DEBUG
management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      enabled: true
    restart:
      enabled: true
    info:
      enabled: true
    gateway:
      enabled: true